### ISSUE TITLE
Documentation missing explanation on getter/setter macros and obj.@var syntax

### ISSUE THREAD

**Issue by paddor** [crystal-lang/crystal-book#14]
(Moved here from crystal-lang/crystal#3135)

I just noticed the documentation seems to be missing the description of the `getter`/`setter` macros. The `property` macro is used in the _Structs_ page though.

Also, I saw in source code that `obj.@var` is valid, and I guess it's field access without "method call" (even if there was a getter method that might do something else in addition)? This syntax isn't explained either in the documentation.

Of course one can learn these things through other ways too. Just putting it out there so it won't get forgotten in case the documentation is supposed to be comprehensive. If wanted, and if my assumptions are correct, I could describe it somewhere. But I doubt my writing style is as beautiful as the one in Crystal's documentation. :)

**Comment by asterite** [comment]
You are right, they are used without a previous introduction.

We could maybe not use them at all in the docs, or maybe mention them in some section, but it can always happen that you skip some sections and later you miss that.

For reference, `getter`, `setter` and `property` are macros defined in `Object`: https://crystal-lang.org/api/0.18.7/Object.html , and they are documented there. They are very common, so I'm hesitant about skipping them entirely in the docs, but I don't know where would I put them either...

**Comment by paddor** [comment]
What about in [Methods and Instance Variables](https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html)? I just noticed the second snippet there is missing a `getter age` anyway and doesn't compile.

In addition, they could be mentioned again in _Structs_.

Regarding the `obj.@var` syntax, I think it could be mentioned on the same page, that it'll work without a getter/setter defined, but in most cases probably is discouraged as it is too low-level and doesn't help encapsulation. (Tell me if I'm wrong.)

**Comment by RX14** [comment]
I wouldn't mention `obj.@var` syntax at all, and I really think it should be somewhat of an "open secret" that's only used in the standard library. Mentioning the getter, setter and property macros would also probably be a good idea, Methods and Instance Variables looks like a good place.

**Comment by barisbalic** [comment]
I missed the `getter` / `setter` macros exactly as @asterite suggests so I think making them more prominent would be good, when I remembered that there was 'something' in the guides, I went straight to the [Methods and Instance Variables](https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html) page, exactly as @paddor suggests.  I realise I'm just one person, but that feels right.

**Comment by RX14** [comment]
I think we should have a link to the api docs for the macros from the "Methods and Instance Variables" page.

**Comment by andyfleming** [comment]
I agree with @barisbalic. I was just discussing this with @RX14. I was expecting to see them on the **Methods and Instance Variables** page.

**Comment by mverzilli** [comment]
I'll close this in favor of #62. Summary of the discussion here:

1. The book's not mentioning `getter` and `setter`. [Methods and Instance Variables](https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html) seems to be the most sensible section to introduce them. At this point of the book, we should just show what they do and how to use them, delaying any mention of the fact that they're macros to more advanced sections.
1. `property` is accidentally introduced in the `Structs` page. If we add `getter` and `setter` to _Methods and Instance Variables_, we should probably also add `property` there. `Structs` comes later on, so it seems ok to leave `property` there (but we could add a link from `Structs` to _Methods and Instance Variables_ to properly close the loop).
1. `obj.@var` exists but is not documented. We don't want to document it at all, because it's mostly a low-level hack that users should never, ever, resort to. 
1. We should add a link to macros from _Methods and Instance Variables_. 
1. Eventually we could leverage the fact that `getter` and `setter` are introduced in _Methods and Instance Variables_ to enhance the `Macros` section (along the lines of: "Remember `getter` and `setter`? Well, they're macros!").

cc: @andyfleming
