### ISSUE TITLE
Add documentation for GitHub actions in guide

### ISSUE THREAD

**Issue by arschles** [crystal-lang/crystal-book#397]
In the [CI](https://crystal-lang.org/reference/guides/continuous_integration.html) guide, there are currently guides for Travis CI and Circle CI. I use GitHub actions a lot, so it would be really helpful to have a guide for it as well. 

I recently wrote a simple guide for using actions for the Lucky framework here: 
https://github.com/luckyframework/website/pull/283, and I'm happy to write something up in the book also.

Is it ok for me to submit a PR?

**Comment by bcardiff** [comment]
Now that https://github.com/oprypin/install-crystal maybe a guide that matches the existing ones can be added. I haven't checked @oprypin's actions yet. I like that they cover non docker installations also.

I wouldn't mention how to include ameba yet since it's not something we are covering uniformly yet. Maybe later.

**Comment by straight-shoota** [comment]
Resolved by
