### ISSUE TITLE
Naming scheme for version branches

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-book#568]
I don't think it's a good idea to name the version branches (introduced in #529) *just* by the version number (e.g. `1.2`). Some kind of prefix would be appreciated for easy identification. I'm thinking of `v1.2` or `release/1.2` (akin to the main repo).

Alternatively, I'm wondering if we even *need* to have individual branches. General improvements are going into the branch for the latest version, and documentation about unreleased changes goes into the branch for the next version. So we essentially just need two branches, `latest` and `master` (or `master` and `next`?) and occasionally merge latest into next. All older versions could just be a tag. They're unlikely to be changed once they're outdated.
The exact number of branches might change if we have multiple supported releases at the same time. But that doesn't change anything really. We still probably won't need a branch for 1.2 or older once we're at 1.3 or newer.
That's just an observation. We can still use branches for older releases. There's probably no harm in that. We could just reconsider if that actually makes sense.

**Comment by oprypin** [comment]
1st part - regarding branch prefix:
It's not really a "release" but I don't have any strong argument against it, other than that it'd probably make the handling much uglier. I'll try and see how adding `release/` prefix works out. Regarding `v` - I reserve it only to tags, so I'd hate to see that.

2nd part - regarding just 2 branches and tags for the rest:
What exactly becomes simpler if you use tags instead of branches? From your suggestion all you'd gain is the *inability* to *ever* update old docs. Which is not nothing, it has negative value, considering that security vulnerabilities in these sites could be a thing.

**Comment by straight-shoota** [comment]
Yeah, unfortunately, I don't have a better idea than `release/` prefix. But I guess `release/1.2` could reasonably be interpreted as "referring to crystal release 1.2".

I honestly don't remember why I considered tags over branches 🤷 I realize it's probably not do any good, so we should just ignore that part.
